

services:
  # API Gateway - Development Override
  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile.dev
    container_name: api_gateway_dev
    volumes:
      - ./gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  # Servicio de Autenticación - Development Override
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    container_name: auth_service_dev
    volumes:
      - ./services/auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your-jwt-secret-key-change-this-in-production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/personas_db
      - AUTH0_DOMAIN=dev-zg58kn127grr7sf6.us.auth0.com
      - AUTH0_CLIENT_ID=eKRUA6UlzZX8DKuCi247gryxqPc8r293
      - AUTH0_CLIENT_SECRET=v3zI0gKGoCgE2u1xqC6PWPLB93aCtOlSbVhmlWeD9Y2lRqhjdxOxE4dzCTXkjn-a
      - AUTH0_CALLBACK_URL=http://localhost:8001/api/auth/login/auth0/callback
      - SESSION_SECRET=your-session-secret-key-change-this-in-production
      - FRONTEND_URL=http://localhost:5173

  # Servicio de Gestión de Personas - Development Override
  personas-service:
    build:
      context: ./services/personas
      dockerfile: Dockerfile.dev
    container_name: personas_service_dev
    volumes:
      - ./services/personas:/app
      - /app/node_modules
      - personas_uploads:/uploads
    environment:
      - NODE_ENV=development

  # Servicio de Consultas - Development Override
  consulta-service:
    build:
      context: ./services/consulta
      dockerfile: Dockerfile.dev
    container_name: consulta_service_dev
    volumes:
      - ./services/consulta:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    deploy:
      replicas: 1  # Override to 1 replica for development

  # Servicio de NLP - Development Override
  nlp-service:
    build:
      context: ./services/nlp
      dockerfile: Dockerfile.dev
    container_name: nlp_service_dev
    volumes:
      - ./services/nlp:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  # Servicio de Logs - Development Override
  log-service:
    build:
      context: ./services/log
      dockerfile: Dockerfile.dev
    container_name: log_service_dev
    volumes:
      - ./services/log:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  # Frontend React - Development Override (NEW)
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile.dev
    container_name: nextjs_app_dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8001/api
      - NEXT_PUBLIC_APP_NAME=Sistema de Gestión de Personas - Dev
      - NEXT_PUBLIC_APP_VERSION=1.0.0-dev
      - NEXT_PUBLIC_AUTH0_DOMAIN=dev-zg58kn127grr7sf6.us.auth0.com
      - NEXT_PUBLIC_AUTH0_CLIENT_ID=eKRUA6UlzZX8DKuCi247gryxqPc8r293
      - NEXT_PUBLIC_AUTH0_REDIRECT_URI=http://localhost:3000/auth/callback
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - gateway

  # Frontend Flask - Development Override (LEGACY - commented out)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: flask_app_dev
  #   volumes:
  #     - ./frontend:/app
  #     - /app/__pycache__
  #   environment:
  #     - FLASK_ENV=development
  #     - FLASK_DEBUG=1
